# Travaux Pratique : introduction PyTorch, Tensors et Tensor Operations

PyTorch est la bibliothèque de tenseurs hautes performances la plus optimisée pour le calcul de tâches d'apprentissage en profondeur sur les GPU (unités de traitement graphique) et les CPU (unités centrales de traitement). PyTorch est une bibliothèque basée sur Python et l'outil Torch fourni par le groupe de recherche sur l'intelligence artificielle de Facebook, qui effectue du calcul scientifique. Les cas d'utilisation où il est le plus fréquemment utilisé incluent le traitement du langage naturel, le traitement d'image, la vision par ordinateur, l'analyse des données des médias sociaux et le traitement des données des capteurs. Bien que PyTorch fournisse une large collection de bibliothèques et de modules de calcul, trois modules sont très importants.

La documentation est disponible sur ce [lien](https://pytorch.org/docs/stable/index.html)

## 1 Utilisation Tensors

## fonction basique
**Nous pouvons vérifier si un objet en Python est un objet tenseur en utilisant la syntaxe suivante.**

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.version.__version__

'1.7.1'

In [3]:
x = [12,23,34,45,56,67,78]

In [4]:
torch.is_tensor(x)

False

**La fonction is_storage vérifie si l'objet est stocké en tant qu'objet tenseur:**

In [6]:
torch.is_storage(x)

False

**Maintenant, créons un objet contenant des nombres aléatoires de Torch, similaire à la bibliothèque NumPy. 
Nous pouvons vérifier le tenseur et le type de stockage. La documentation est disponible [ici](https://pytorch.org/docs/stable/generated/torch.rand.html)**

In [7]:
y = torch.randn(1,2,3,4,5)

In [8]:
torch.is_tensor(y)

True

In [9]:
torch.is_storage(y)

False

In [10]:
torch.numel(y) # the total number of elements in the input Tensor

120

**L'objet y est un tenseur ; cependant, il n'est pas stocké. Pour vérifier le nombre total d'éléments dans l'objet tenseur d'entrée, 
la fonction d'élément numérique peut être utilisée. Le script suivant est un autre exemple de création de valeurs nulles 
dans un tenseur 2D et de comptage des éléments numériques qu'il contient. [documentation](https://pytorch.org/docs/stable/generated/torch.zeros.html)**

In [11]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
torch.numel(torch.zeros(4,4))

16

**Comme les opérations NumPy, la fonction eye crée une matrice diagonale, dont les éléments diagonaux ont des uns, et les éléments hors diagonale ont des zéros. La fonction eye peut être manipulée en fournissant l'option de dimension.** [documentation]()

In [13]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [16]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [18]:
import numpy as np #importation de la biblio numpy 
x1 = np.array(x)

**On peut créer des tensors à partir de array numpy [documentation](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)**

In [19]:
x1

array([12, 23, 34, 45, 56, 67, 78])

In [20]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78], dtype=torch.int32)

On peut créer un tenseur unidimensionnel de pas de taille dont les valeurs sont régulièrement espacées du début à la fin, inclus.

In [21]:
torch.linspace(2, 10, steps=25) #linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [22]:
torch.linspace(-10, 10, steps=15)

tensor([-10.0000,  -8.5714,  -7.1429,  -5.7143,  -4.2857,  -2.8571,  -1.4286,
          0.0000,   1.4286,   2.8571,   4.2857,   5.7143,   7.1429,   8.5714,
         10.0000])

In [23]:
torch.logspace(start=-10, end=10, steps=15) #logarithmic spacing

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

## Procédé aléatoire 

La génération de nombres aléatoires est un processus courant en science des données pour générer ou rassembler des exemples de points de données dans un espace afin de simuler la structure des données. 

Des nombres aléatoires peuvent être générés à partir d'une distribution statistique, de deux valeurs quelconques ou d'une distribution prédéfinie. Comme les fonctions NumPy, le nombre aléatoire peut être généré à l'aide de l'exemple suivant. 

La distribution uniforme est définie comme une distribution où chaque résultat a une probabilité égale de se produire ; par conséquent, les probabilités d'événement sont constantes.

In [26]:
# random numbers from a uniform distribution between the values 
# 0 and 1
torch.rand(10)

tensor([0.3409, 0.8690, 0.9251, 0.1052, 0.5562, 0.7348, 0.4306, 0.4040, 0.7967,
        0.2775])

In [27]:
torch.rand(4, 5) 
# random values between 0 and 1 and fillied with a matrix of 
# size rows 4 and columns 5

tensor([[0.9182, 0.9273, 0.9845, 0.1164, 0.8071],
        [0.8337, 0.7950, 0.6537, 0.0297, 0.9685],
        [0.5582, 0.2454, 0.6831, 0.8529, 0.4715],
        [0.0462, 0.0212, 0.9521, 0.3459, 0.4964]])

In [28]:
#random numbers from a normal distribution, 
#with mean =0 and standard deviation =1
torch.randn(10)

tensor([-2.2214e+00,  3.3436e+00, -9.1005e-01,  3.8819e-01,  1.8948e-04,
        -1.2541e+00,  3.9365e-01, -9.2636e-01, -1.7877e+00,  2.7802e-01])

In [29]:
torch.randn(4, 5)

tensor([[ 0.0023,  0.9481, -0.5481, -0.1665, -0.7035],
        [ 1.3833,  2.1726, -0.6313, -0.9048, -0.3696],
        [ 0.6735, -0.5608,  0.6813, -0.0672, -0.0499],
        [-0.0032,  1.2302,  0.8534,  0.1668, -0.1698]])

**Pour sélectionner des valeurs aléatoires dans une plage de valeurs à l'aide d'une permutation aléatoire, il faut d'abord définir la plage.**

**Cette plage peut être créée à l'aide de la fonction d'arrangement. Lorsque vous utilisez la fonction d'arrangement, vous devez définir la taille du pas, qui place toutes les valeurs dans un espace à distance égale. Par défaut, la taille du pas est 1.** [documentation](https://pytorch.org/docs/stable/generated/torch.randperm.html)

In [30]:
#selecting values from a range, this is called random permutation
torch.randperm(10)

tensor([7, 2, 0, 3, 8, 1, 6, 4, 9, 5])

In [31]:
#usage of range function 
torch.arange(10, 40,2) #step size 2

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [32]:
torch.arange(10,40) #step size 1

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

**Pour trouver les valeurs minimales et maximales dans un tenseur 1D, argmin et argmax peuvent être utilisés. La dimension doit être mentionnée si l'entrée est une matrice afin de rechercher des valeurs minimales le long des lignes ou des colonnes.** [documentation](https://pytorch.org/docs/stable/generated/torch.argmax.html) 

In [5]:
torch.argmin(d,dim=1)

NameError: name 'd' is not defined

In [118]:
torch.argmax(d,dim=1)

tensor([3, 4, 1, 2])

Maintenant, créons un exemple de tenseur 2D et effectuons l'indexation et la concaténation en utilisant l'opération concat sur les tenseurs.

In [122]:
#indexing and performing operation on the tensors
x = torch.randn(4,5)

In [133]:
print(x)
print(x.shape)

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])
torch.Size([4, 5])


In [124]:
#concatenate two tensors
torch.cat((x,x))

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670],
        [ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])

In [125]:
#concatenate n times based on array size
torch.cat((x,x,x))

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670],
        [ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670],
        [ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])

In [132]:
#concatenate n times based on array size, over column
concatenate_tensors = torch.cat((x,x,x),1)
print(concatenate_tensors)
print(concatenate_tensors.shape)

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380,  0.0190,  0.0220,  1.1532,
         -0.3393, -1.5380,  0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825, -1.0248, -0.3781,  0.9257,
          0.9247,  0.1825, -1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692, -0.0737,  0.3147,  0.8504,
          1.0534,  0.3692, -0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670,  0.0628, -0.3297, -1.7970,
          0.8728,  0.7670,  0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])
torch.Size([4, 15])


In [127]:
#concatenate n times based on array size, over rows
torch.cat((x,x),0)

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670],
        [ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])

Un tenseur peut être divisé en plusieurs morceaux. Ces petits morceaux peuvent être créés le long de lignes et de colonnes. L'exemple suivant montre un exemple de tenseur de taille (4,4). [documentation](https://pytorch.org/docs/stable/generated/torch.chunk.html)

In [134]:
help(torch.chunk) # on peut également utiliser la commande help pour obtenir la documentation de la fonction

Help on built-in function chunk:

chunk(...)
    chunk(input, chunks, dim=0) -> List of Tensors
    
    Splits a tensor into a specific number of chunks. Each chunk is a view of
    the input tensor.
    
    Last chunk will be smaller if the tensor size along the given dimension
    :attr:`dim` is not divisible by :attr:`chunks`.
    
    Arguments:
        input (Tensor): the tensor to split
        chunks (int): number of chunks to return
        dim (int): dimension along which to split the tensor



In [6]:
a = torch.randn(4, 4)
print(a)
chunk_tensor_one, chunk_tensor_two = torch.chunk(a,3)
print(chunk_tensor_one)
print(chunk_tensor_one.shape)

tensor([[ 0.8275,  0.2037,  0.0178, -1.1676],
        [-0.5166, -1.5855,  0.9845, -0.7442],
        [ 1.2453,  1.2474,  0.7227, -0.4241],
        [ 0.3165, -1.8222,  0.2559, -0.9941]])
tensor([[ 0.8275,  0.2037,  0.0178, -1.1676],
        [-0.5166, -1.5855,  0.9845, -0.7442]])
torch.Size([2, 4])


In [47]:
torch.chunk(a,2,0)

(tensor([[ 0.7511, -0.2865,  1.3605,  0.0829],
         [-0.2232,  1.5162,  0.7597,  1.0610]]),
 tensor([[ 0.6291,  0.7295,  1.1682, -0.5936],
         [ 1.7154,  0.2782, -1.6784,  0.2454]]))

In [48]:
torch.chunk(a,2,1)

(tensor([[ 0.7511, -0.2865],
         [-0.2232,  1.5162],
         [ 0.6291,  0.7295],
         [ 1.7154,  0.2782]]),
 tensor([[ 1.3605,  0.0829],
         [ 0.7597,  1.0610],
         [ 1.1682, -0.5936],
         [-1.6784,  0.2454]]))

**La fonction gather collecte les éléments d'un tenseur et les place dans un autre tenseur à l'aide d'un argument d'index. La position de l'index est déterminée par la fonction LongTensor dans PyTorch.** [documentation](https://pytorch.org/docs/stable/generated/torch.gather.html)

In [143]:
torch.Tensor([[11,12],[23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [149]:
torch.gather(torch.Tensor([[11,12],[23,24]]), 0, 
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 12.],
        [23., 12.]])

In [148]:
 torch.LongTensor([[0,0],[1,0]]) 
#the 1D tensor containing the indices to index

tensor([[0, 0],
        [1, 0]])

In [154]:
a = torch.randn(4, 4)
print(a)
torch.gather(a, 1, 
             torch.LongTensor([[2,3],[3,1]]))

tensor([[ 0.3541, -0.8554,  1.4224, -1.1067],
        [ 2.2689, -2.2510, -1.0115,  0.3828],
        [-1.0022,  0.0939, -1.5120,  0.8782],
        [-0.8629, -0.9917,  0.8485,  0.7376]])


tensor([[ 1.4224, -1.1067],
        [ 0.3828, -2.2510]])

In [53]:
indices = torch.LongTensor([0, 2])

In [54]:
torch.index_select(a, 0, indices)

tensor([[-0.0403, -0.8753,  2.0183, -0.9703],
        [-1.1656,  0.5954,  0.2671, -1.9146]])

In [55]:
torch.index_select(a, 1, indices)

tensor([[-0.0403,  2.0183],
        [ 0.1292, -0.8912],
        [-1.1656,  0.2671],
        [ 0.4502,  0.3058]])

**C'est une pratique courante de vérifier les valeurs non manquantes dans un tenseur, l'objectif est d'identifier les éléments non nuls dans un grand tenseur.** [documentation](https://pytorch.org/docs/stable/generated/torch.nonzero.html).

In [156]:
#identify null input tensors using nonzero function
torch.nonzero(torch.tensor([10,0,23,0,0.0]))

tensor([[0],
        [2]])

In [157]:
torch.nonzero(torch.Tensor([10,0,23,0,0.0]))

tensor([[0],
        [2]])

**La restructuration des tenseurs d'entrée en tenseurs plus petits accélère non seulement le processus de calcul, mais aide également au calcul distribué. La fonction split divise un long tenseur en plus petits tenseurs. [documentation](https://pytorch.org/docs/stable/generated/torch.split.html)**

In [58]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [59]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

**Voyons maintenant des exemples de la façon dont le tenseur d'entrée peut être redimensionné compte tenu de la difficulté de calcul. La fonction de transposition est principalement utilisée pour remodeler les tenseurs. Il existe deux manières d'écrire la fonction de transposition : .t et .transpose.** [documentation](https://pytorch.org/docs/stable/generated/torch.transpose.html)

In [60]:
torch.zeros(3,2,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [61]:
torch.zeros(3,2,4).size()

torch.Size([3, 2, 4])

In [62]:
#how to reshape the tensors along a new dimension

In [63]:
x

tensor([[-0.7857,  0.3849,  0.2655, -0.1885, -0.9176],
        [-0.1385,  1.7135, -0.2665,  1.3139,  0.6850],
        [ 0.9837, -1.0935, -0.5328, -0.3283, -0.4980],
        [ 0.4214, -0.0594, -1.1553, -0.4805,  0.7077]])

In [64]:
x.t() #transpose is one option to change the shape of the tensor

tensor([[-0.7857, -0.1385,  0.9837,  0.4214],
        [ 0.3849,  1.7135, -1.0935, -0.0594],
        [ 0.2655, -0.2665, -0.5328, -1.1553],
        [-0.1885,  1.3139, -0.3283, -0.4805],
        [-0.9176,  0.6850, -0.4980,  0.7077]])

In [65]:
# transpose partially based on rows and columns

In [66]:
x.transpose(1,0)

tensor([[-0.7857, -0.1385,  0.9837,  0.4214],
        [ 0.3849,  1.7135, -1.0935, -0.0594],
        [ 0.2655, -0.2665, -0.5328, -1.1553],
        [-0.1885,  1.3139, -0.3283, -0.4805],
        [-0.9176,  0.6850, -0.4980,  0.7077]])

**La fonction unbind supprime une dimension d'un tenseur. Pour supprimer la ligne de dimension, la valeur 0 doit être transmise. Pour supprimer une colonne, la valeur 1 doit être transmise** [documentation](https://pytorch.org/docs/stable/generated/torch.unbind.html)

In [160]:
x

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])

In [161]:
torch.unbind(x,1) #dim=1 removing a column

(tensor([ 0.0190, -1.0248, -0.0737,  0.0628]),
 tensor([ 0.0220, -0.3781,  0.3147, -0.3297]),
 tensor([ 1.1532,  0.9257,  0.8504, -1.7970]),
 tensor([-0.3393,  0.9247,  1.0534,  0.8728]),
 tensor([-1.5380,  0.1825,  0.3692,  0.7670]))

In [70]:
torch.unbind(x) #dim=0 removing a row

(tensor([-0.7857,  0.3849,  0.2655, -0.1885, -0.9176]),
 tensor([-0.1385,  1.7135, -0.2665,  1.3139,  0.6850]),
 tensor([ 0.9837, -1.0935, -0.5328, -0.3283, -0.4980]),
 tensor([ 0.4214, -0.0594, -1.1553, -0.4805,  0.7077]))

In [71]:
x

tensor([[-0.7857,  0.3849,  0.2655, -0.1885, -0.9176],
        [-0.1385,  1.7135, -0.2665,  1.3139,  0.6850],
        [ 0.9837, -1.0935, -0.5328, -0.3283, -0.4980],
        [ 0.4214, -0.0594, -1.1553, -0.4805,  0.7077]])

# comment calculer les fonctions mathématiques de base

In [162]:
torch.abs(torch.FloatTensor([-10, -23, 3.000]))

tensor([10., 23.,  3.])

In [163]:
#adding value to the existing tensor, scalar addition
torch.add(x,20)

tensor([[20.0190, 20.0220, 21.1532, 19.6607, 18.4620],
        [18.9752, 19.6219, 20.9257, 20.9247, 20.1825],
        [19.9263, 20.3147, 20.8504, 21.0534, 20.3692],
        [20.0628, 19.6703, 18.2030, 20.8728, 20.7670]])

In [164]:
x

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393, -1.5380],
        [-1.0248, -0.3781,  0.9257,  0.9247,  0.1825],
        [-0.0737,  0.3147,  0.8504,  1.0534,  0.3692],
        [ 0.0628, -0.3297, -1.7970,  0.8728,  0.7670]])

In [165]:
# scalar multiplication
torch.mul(x,2)

tensor([[ 0.0381,  0.0440,  2.3064, -0.6787, -3.0759],
        [-2.0497, -0.7561,  1.8515,  1.8494,  0.3651],
        [-0.1474,  0.6294,  1.7008,  2.1068,  0.7384],
        [ 0.1256, -0.6593, -3.5939,  1.7456,  1.5339]])

In [77]:
x

tensor([[-0.7857,  0.3849,  0.2655, -0.1885, -0.9176],
        [-0.1385,  1.7135, -0.2665,  1.3139,  0.6850],
        [ 0.9837, -1.0935, -0.5328, -0.3283, -0.4980],
        [ 0.4214, -0.0594, -1.1553, -0.4805,  0.7077]])

Les opérations mathématiques combinées, telles que l'expression d'équations linéaires sous forme d'opérations tensorielles, peuvent être effectuées à l'aide de l'exemple de script suivant. Ici, nous exprimons l'objet résultat y comme une combinaison linéaire des valeurs bêta multipliées par l'objet x indépendant, plus le terme constant.

In [78]:
# how do we represent the equation in the form of a tensor

In [79]:
# y = intercept + (beta * x)

In [166]:
intercept = torch.randn(1)
intercept

tensor([0.9534])

In [167]:
x = torch.randn(2, 2)
x

tensor([[-0.2428,  0.4882],
        [-1.7444, -2.9053]])

In [168]:
beta = 0.7456
beta

0.7456

In [169]:
torch.mul(x,beta)

tensor([[-0.1810,  0.3640],
        [-1.3006, -2.1662]])

In [170]:
torch.add(x,beta,intercept)

tensor([[ 0.4681,  1.1991],
        [-1.0335, -2.1945]])

In [171]:
torch.mul(intercept,x)

tensor([[-0.2315,  0.4655],
        [-1.6631, -2.7699]])

In [172]:
torch.mul(x,beta)

tensor([[-0.1810,  0.3640],
        [-1.3006, -2.1662]])

In [173]:
## y = intercept + (beta * x)
torch.add(torch.mul(intercept,x),torch.mul(x,beta)) # tensor y

tensor([[-0.4125,  0.8295],
        [-2.9637, -4.9361]])

In [88]:
# how to round up tensor values
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [89]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [90]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

**Limiter les valeurs de n'importe quel tenseur dans une certaine plage peut être fait en utilisant l'argument minimum et maximum et en utilisant la fonction clamp. La même fonction peut appliquer le minimum et le maximum en parallèle ou l'un d'eux à n'importe quel tenseur, qu'il soit 1D ou 2D ; 1D est la version beaucoup plus simple. L'exemple suivant montre l'implémentation dans un scénario 2D.** [documentation](https://pytorch.org/docs/stable/generated/torch.clamp.html)

In [91]:
# truncate the values in a range say 0,1
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [92]:
#truncate with only lower limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [93]:
#truncate with only upper limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [94]:
#scalar division
torch.div(x,0.10)

tensor([[17.5031,  4.0656],
        [-7.2563, -0.9320]])

In [95]:
#compute the exponential of a tensor
torch.exp(x)

tensor([[5.7564, 1.5016],
        [0.4840, 0.9110]])

In [96]:
np.exp(x)

tensor([[5.7564, 1.5016],
        [0.4840, 0.9110]])

In [97]:
#how to get the fractional portion of each tensor

In [98]:
torch.add(x,10)

tensor([[11.7503, 10.4066],
        [ 9.2744,  9.9068]])

In [99]:
torch.frac(torch.add(x,10))

tensor([[0.7503, 0.4066],
        [0.2744, 0.9068]])

In [100]:
# compute the log of the values in a tensor

In [101]:
x

tensor([[ 1.7503,  0.4066],
        [-0.7256, -0.0932]])

In [102]:
torch.log(x) #log of negatives are nan

tensor([[ 0.5598, -0.9000],
        [    nan,     nan]])

In [103]:
# to rectify the negative values do a power tranforamtion
torch.pow(x,2)

tensor([[3.0636, 0.1653],
        [0.5265, 0.0087]])

In [104]:
# rounding up similar to numpy

In [105]:
x

tensor([[ 1.7503,  0.4066],
        [-0.7256, -0.0932]])

In [106]:
np.round(x)

tensor([[ 2.,  0.],
        [-1., -0.]])

In [107]:
torch.round(x)

tensor([[ 2.,  0.],
        [-1., -0.]])

**Pour calculer les fonctions de transformation (c'est-à-dire sigmoïde, tangente hyperbolique, fonction de base radiale, etc., qui sont les fonctions de transfert les plus couramment utilisées dans l'apprentissage en profondeur), vous devez construire les tenseurs. L'exemple de script suivant montre comment créer une fonction sigmoïde et l'appliquer sur un tenseur.**

In [109]:
x

tensor([[ 1.7503,  0.4066],
        [-0.7256, -0.0932]])

In [110]:
torch.sigmoid(x)

tensor([[0.8520, 0.6003],
        [0.3262, 0.4767]])

In [111]:
# finding the square root of the values

In [112]:
x

tensor([[ 1.7503,  0.4066],
        [-0.7256, -0.0932]])

In [113]:
torch.sqrt(x)

tensor([[1.3230, 0.6376],
        [   nan,    nan]])