In [2]:
import torch

## TP Introduction Distributions et Autograd Torch  

In [4]:
torch.manual_seed(1234)

**Les nombres aléatoires peuvent être générés à partir d'une distribution statistique. La fonction de densité de probabilité de la distribution uniforme continue est définie par la formule suivante.**
$$f(x) =     \begin{cases}
      \frac{1}{b-a} & \text{for $a \leq x \leq b$ }\\
      0 & \text{for $x < a $ or $x > b$}\\
    \end{cases}$$

In [5]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [6]:
torch.Tensor(4, 4).uniform_(0, 1) #random number from uniform distribution

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

**En statistique, la distribution de Bernoulli est considérée comme la distribution de probabilité discrète, qui a deux résultats possibles. Si l'événement se produit, alors la valeur est 1, et si l'événement ne se produit pas, alors la valeur est 0.**
$$f(x) =     \begin{cases}
      q = (1-p) & \text{for $k=0$}\\
      p & \text{for $k=1$}\\
    \end{cases}$$

In [7]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [8]:
#how to perform sampling from a multinomial distribution

In [9]:
torch.Tensor([10, 10, 13, 10,34,45,65,67,87,89,87,34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [14]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  3)

tensor([10,  2,  3])

In [12]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  5, replacement=True)

tensor([11,  4,  4,  8,  6])

**L'initialisation des poids à partir de la distribution normale est une méthode utilisée pour ajuster un réseau neuronal, cnn et rnn. Examinons le processus de création d'un ensemble de poids aléatoires générés à partir d'une distribution normale.**

In [20]:
torch.normal(0,1, size=(1,4))

tensor([[-0.0845,  0.5903, -1.0032, -1.7873]])

In [14]:
torch.normal(mean=torch.arange(1., 11.), 
             std=torch.arange(1, 0, -0.1))

tensor([-0.0413,  2.0632,  3.4637,  3.9581,  5.1089,  5.6602,  6.8973,  7.4543,
         9.0422, 10.0337])

In [15]:
torch.normal(mean=0.5, 
             std=torch.arange(1., 6.))

tensor([1.5812, 2.9873, 3.1912, 0.1866, 3.2741])

In [16]:
torch.normal(mean=0.5, 
             std=torch.arange(0.2,0.6))

tensor([0.4939])

In [17]:
#computing the descriptive statistics: mean
torch.mean(torch.tensor([10., 10., 13., 10., 34., 
                         45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [18]:
# mean across rows and across columns
d = torch.randn(4, 5)
d

tensor([[ 0.9570, -0.5510,  2.6617,  2.1479,  1.2907],
        [ 0.2612, -0.5862, -1.5105, -0.1225,  0.8078],
        [-1.1421,  2.0506,  0.5289, -0.5447,  0.8097],
        [ 1.1226, -1.6121,  0.4752,  0.5868, -0.2878]])

In [19]:
torch.mean(d,dim=0)

tensor([ 0.2997, -0.1746,  0.5388,  0.5169,  0.6551])

In [20]:
torch.mean(d,dim=1)

tensor([ 1.3013, -0.2300,  0.3405,  0.0569])

In [21]:
#compute median
torch.median(d,dim=0)

(tensor([ 0.2612, -0.5862,  0.4752, -0.1225,  0.8078]),
 tensor([1, 1, 3, 1, 1]))

In [22]:
torch.median(d,dim=1)

(tensor([ 1.2907, -0.1225,  0.5289,  0.4752]), tensor([4, 3, 2, 2]))

In [23]:
# compute the mode
torch.mode(d)

(tensor([-0.5510, -1.5105, -1.1421, -1.6121]), tensor([1, 2, 0, 1]))

In [24]:
torch.mode(d,dim=0)

(tensor([-1.1421, -1.6121, -1.5105, -0.5447, -0.2878]),
 tensor([2, 3, 1, 2, 3]))

In [25]:
torch.mode(d,dim=1)

(tensor([-0.5510, -1.5105, -1.1421, -1.6121]), tensor([1, 2, 0, 1]))

In [26]:
#compute the standard deviation
torch.std(d)

tensor(1.1810)

In [27]:
torch.std(d,dim=0)

tensor([1.0311, 1.5630, 1.7040, 1.1833, 0.6684])

In [28]:
torch.std(d,dim=1)

tensor([1.2366, 0.8799, 1.2412, 1.0601])

In [29]:
#compute variance
torch.var(d)

tensor(1.3948)

In [30]:
torch.var(d,dim=0)

tensor([1.0632, 2.4430, 2.9035, 1.4003, 0.4467])

In [31]:
torch.var(d,dim=1)

tensor([1.5293, 0.7741, 1.5405, 1.1239])

In [32]:
# compute min and max
torch.min(d)

tensor(-1.6121)

In [33]:
torch.min(d,dim=0)

(tensor([-1.1421, -1.6121, -1.5105, -0.5447, -0.2878]),
 tensor([2, 3, 1, 2, 3]))

In [34]:
torch.min(d,dim=1)

(tensor([-0.5510, -1.5105, -1.1421, -1.6121]), tensor([1, 2, 0, 1]))

In [35]:
torch.max(d)

tensor(2.6617)

In [36]:
torch.max(d,dim=0)

(tensor([1.1226, 2.0506, 2.6617, 2.1479, 1.2907]), tensor([3, 2, 0, 0, 0]))

In [37]:
torch.max(d,dim=1)

(tensor([2.6617, 0.8078, 2.0506, 1.1226]), tensor([2, 4, 1, 0]))

In [38]:
# sorting a tensor
torch.sort(d)

(tensor([[-0.5510,  0.9570,  1.2907,  2.1479,  2.6617],
         [-1.5105, -0.5862, -0.1225,  0.2612,  0.8078],
         [-1.1421, -0.5447,  0.5289,  0.8097,  2.0506],
         [-1.6121, -0.2878,  0.4752,  0.5868,  1.1226]]),
 tensor([[1, 0, 4, 3, 2],
         [2, 1, 3, 0, 4],
         [0, 3, 2, 4, 1],
         [1, 4, 2, 3, 0]]))

In [39]:
torch.sort(d,dim=0)

(tensor([[-1.1421, -1.6121, -1.5105, -0.5447, -0.2878],
         [ 0.2612, -0.5862,  0.4752, -0.1225,  0.8078],
         [ 0.9570, -0.5510,  0.5289,  0.5868,  0.8097],
         [ 1.1226,  2.0506,  2.6617,  2.1479,  1.2907]]),
 tensor([[2, 3, 1, 2, 3],
         [1, 1, 3, 1, 1],
         [0, 0, 2, 3, 2],
         [3, 2, 0, 0, 0]]))

In [40]:
torch.sort(d,dim=0,descending=True)

(tensor([[ 1.1226,  2.0506,  2.6617,  2.1479,  1.2907],
         [ 0.9570, -0.5510,  0.5289,  0.5868,  0.8097],
         [ 0.2612, -0.5862,  0.4752, -0.1225,  0.8078],
         [-1.1421, -1.6121, -1.5105, -0.5447, -0.2878]]),
 tensor([[3, 2, 0, 0, 0],
         [0, 0, 2, 3, 2],
         [1, 1, 3, 1, 1],
         [2, 3, 1, 2, 3]]))

In [41]:
torch.sort(d,dim=1,descending=True)

(tensor([[ 2.6617,  2.1479,  1.2907,  0.9570, -0.5510],
         [ 0.8078,  0.2612, -0.1225, -0.5862, -1.5105],
         [ 2.0506,  0.8097,  0.5289, -0.5447, -1.1421],
         [ 1.1226,  0.5868,  0.4752, -0.2878, -1.6121]]),
 tensor([[2, 3, 4, 0, 1],
         [4, 0, 3, 1, 2],
         [1, 4, 2, 3, 0],
         [0, 3, 2, 4, 1]]))

## Représentation des variables dans Pytorch

**Dans PyTorch, les algorithmes sont représentés sous la forme d'un graphe de calcul. Une variable est considérée comme une représentation autour de l'objet tenseur.** 

**Fondamentalement, une variable PyTorch est un nœud dans un graphe de calcul qui stocke des données et des gradients. Lors de la formation d'un modèle de réseau de neurones, après chaque itération, nous devons calculer le gradient de la fonction de perte par rapport aux paramètres du modèle, tels que les poids et les biais.**

**Après cela, nous mettons généralement à jour les poids à l'aide de l'algorithme de descente de gradient. Dans une structure de graphe informatique, le séquencement et l'ordre des tâches sont très importants.**

In [31]:
from torch.autograd import Variable

# Comment ça fonctionne ?

**Un exemple de la façon dont une variable est utilisée pour créer un graphique de calcul est affiché dans le script suivant. Il y a trois objets variables autour des tenseurs x1, x2 et x3 avec des points aléatoires générés à partir de a = 12 et b = 23.** 

**Le calcul du graphe implique uniquement la multiplication et l'addition, et le résultat final avec le gradient est affiché. La dérivée partielle de la fonction de perte par rapport aux poids et aux biais dans un modèle de réseau de neurones est obtenue dans PyTorch à l'aide du module Autograd.** 

**Les variables sont spécifiquement conçues pour conserver les valeurs modifiées lors de l'exécution d'une rétropropagation dans un modèle de réseau neuronal lorsque les paramètres du modèle changent. Le type de variable n'est qu'un wrapper autour du tenseur.** 


**Il a trois propriétés : data, grad et function.**

In [32]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [33]:
a, b = 12,23
x1 = Variable(torch.randn(a,b),
            requires_grad=True)
x2 = Variable(torch.randn(a,b),
            requires_grad=True)
x3 =Variable(torch.randn(a,b),
            requires_grad=True)

In [39]:
c = x1 * x2

d = a + x3

e = torch.sum(d)

e.backward()


In [46]:
x1.data

tensor([[-1.2777e+00, -7.4283e-01,  9.7109e-01,  3.5512e-01,  8.5619e-01,
         -3.6345e-01, -1.5518e-01, -1.2282e+00, -8.0385e-01, -4.5301e-01,
         -2.2171e-01, -2.0901e+00, -1.2658e+00, -1.8761e+00, -6.0664e-01,
          7.4703e-01,  3.4744e-01,  2.8557e-01, -4.9545e-02,  6.2245e-01,
          1.6573e-01,  3.1583e-01,  2.4915e-01],
        [-4.9784e-01, -1.6970e-02, -2.8298e-01, -6.4459e-01, -1.9885e-02,
          1.6222e+00,  1.4239e+00,  9.0691e-01,  7.6310e-02,  3.4223e-01,
         -2.8727e-01, -6.7258e-01,  8.8433e-01, -6.6589e-01, -7.3347e-01,
         -2.7599e-01,  5.5485e-01, -6.0949e-02,  2.1073e+00, -9.9300e-01,
          1.4080e+00,  2.5969e-01,  8.0760e-01],
        [-1.2618e+00, -7.7109e-01,  1.3940e+00,  6.0595e-01,  2.2088e-01,
         -8.2452e-01, -2.5581e-02, -1.9850e+00, -3.7880e-01, -1.5030e+00,
         -1.7534e-02, -9.1940e-01, -9.3890e-01, -1.9421e+00,  9.8052e-01,
         -7.4463e-02, -7.1181e-01,  1.6136e+00, -9.7924e-01,  8.2851e-01,
         -2.50

In [47]:
x2.data

tensor([[ 1.2884e+00, -3.9304e-01, -2.4394e-01, -3.8565e-01, -9.5948e-02,
          9.4557e-01, -1.2708e+00,  2.9587e-01,  3.9360e-01, -6.2567e-02,
          5.7281e-01, -2.5252e-01, -7.3179e-02, -1.4961e-02,  1.4511e-01,
          2.0197e-01, -5.8638e-01, -4.5538e-02, -7.5597e-01, -1.1689e+00,
         -9.3890e-01,  8.8566e-01,  1.3764e+00],
        [-7.8276e-01,  1.6775e-01,  2.7966e-01, -6.9147e-01, -5.1308e-01,
          1.1427e+00, -1.0126e+00,  1.1602e-01, -1.0350e+00, -6.5080e-01,
         -7.7945e-02, -9.1219e-02,  5.0242e-01, -4.5173e-01, -4.8067e-01,
          5.9066e-01,  1.6343e-01, -2.6001e-01,  1.6992e+00, -2.1036e+00,
         -1.8971e+00,  1.4661e+00,  6.1199e-01],
        [ 7.9935e-01,  9.3007e-01,  2.6468e-01, -4.9206e-01,  3.0550e-01,
          5.8429e-01, -2.1502e+00,  4.1505e-01,  3.1579e-03, -3.8580e-01,
         -7.1814e-01, -1.8785e+00, -2.4006e-01, -1.3253e+00,  1.1415e+00,
         -4.4164e-01,  3.4923e-01, -1.6730e+00,  5.7499e-01,  3.4973e-01,
          1.11

In [48]:
x3.data

tensor([[-0.9961, -1.6909,  0.3310,  0.6250, -0.7701,  1.0212,  0.7180, -0.1095,
          0.0732, -0.4882, -0.1455,  0.9776,  0.3895, -0.6950, -0.0835, -0.0569,
          0.4955, -0.7306,  0.2499,  0.2458,  0.1029, -0.6494, -0.3258],
        [ 0.8149,  0.5885,  1.6232,  0.4841,  0.3293, -1.2471,  0.2117,  1.4315,
          0.0502,  0.9736,  0.0087, -0.7901,  0.0267, -0.3120,  2.4534,  0.7926,
          0.2382,  1.8277,  0.6758, -2.0323, -0.3952,  0.7286,  1.3579],
        [ 1.3583, -0.5818, -1.3091,  1.5569, -1.4629,  0.6109,  0.2401, -0.5455,
          2.9154, -0.1985, -0.2369,  0.1182, -0.8322,  0.1364,  0.4531, -0.1112,
          1.0307, -1.1862,  0.3823,  0.0338,  0.9814, -1.9638, -0.2218],
        [ 0.1477, -0.1875,  0.9963, -1.9271,  0.8275,  1.7371, -0.7392, -0.1709,
          1.2120,  0.9385,  0.3245, -1.6697, -0.5777, -1.4787, -0.2400,  0.4558,
         -1.0911,  0.1566, -1.0629,  0.5193,  0.4776, -0.7194,  0.3499],
        [-0.3935, -0.3622, -3.4058, -0.1108,  1.2183,  0.207

In [49]:
from torch import FloatTensor
from torch.autograd import Variable

a = Variable(FloatTensor([5]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (12, 53, 91, 73)]

w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
Loss = (10 - d)

Loss.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to Loss: {gradient}")

Gradient of w1 w.r.t to Loss: -455.0
Gradient of w2 w.r.t to Loss: -365.0
Gradient of w3 w.r.t to Loss: -60.0
Gradient of w4 w.r.t to Loss: -265.0


In [50]:
# Using forward pass
def forward(x):
    return x * w

In [51]:
import torch
from torch.autograd import Variable

x_data = [11.0, 22.0, 33.0]
y_data = [21.0, 14.0, 64.0]

w = Variable(torch.Tensor([1.0]),  requires_grad=True)  # Any random value

# Before training
print("predict (before training)",  4, forward(4).data[0])

predict (before training) 4 tensor(4.)


In [52]:
# define the Loss function
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

In [53]:
# Run the Training loop
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # Manually set the gradients to zero after updating weights
        w.grad.data.zero_()

    print("progress:", epoch, l.data[0])

	grad:  11.0 21.0 tensor(-220.)
	grad:  22.0 14.0 tensor(2481.6001)
	grad:  33.0 64.0 tensor(-51303.6484)
progress: 0 tensor(604238.8125)
	grad:  11.0 21.0 tensor(118461.7578)
	grad:  22.0 14.0 tensor(-671630.6875)
	grad:  33.0 64.0 tensor(13114108.)
progress: 1 tensor(3.9481e+10)
	grad:  11.0 21.0 tensor(-30279010.)
	grad:  22.0 14.0 tensor(1.7199e+08)
	grad:  33.0 64.0 tensor(-3.3589e+09)
progress: 2 tensor(2.5900e+15)
	grad:  11.0 21.0 tensor(7.7553e+09)
	grad:  22.0 14.0 tensor(-4.4050e+10)
	grad:  33.0 64.0 tensor(8.6030e+11)
progress: 3 tensor(1.6991e+20)
	grad:  11.0 21.0 tensor(-1.9863e+12)
	grad:  22.0 14.0 tensor(1.1282e+13)
	grad:  33.0 64.0 tensor(-2.2034e+14)
progress: 4 tensor(1.1146e+25)
	grad:  11.0 21.0 tensor(5.0875e+14)
	grad:  22.0 14.0 tensor(-2.8897e+15)
	grad:  33.0 64.0 tensor(5.6436e+16)
progress: 5 tensor(7.3118e+29)
	grad:  11.0 21.0 tensor(-1.3030e+17)
	grad:  22.0 14.0 tensor(7.4013e+17)
	grad:  33.0 64.0 tensor(-1.4455e+19)
progress: 6 tensor(4.7966e+34)
	

In [54]:
# After training
print("predict (after training)",  4, forward(4).data[0])

predict (after training) 4 tensor(-9.2687e+24)


In [55]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
print(z)

tensor([[-1.6829, -0.7646, -3.2800,  4.8965],
        [-2.5063,  1.0934, -4.3770,  0.4817],
        [ 3.5295, -4.1107,  1.7744,  0.1032],
        [ 2.7068, -2.3518, -2.9924, -2.2361]])


In [56]:
print('Requires Gradient : %s ' % (z.requires_grad))
print('Volatile : %s ' % (z.volatile))
print('Gradient : %s ' % (z.grad))
print(z.data)

Requires Gradient : False 
Volatile : False 
Gradient : None 
tensor([[-1.6829, -0.7646, -3.2800,  4.8965],
        [-2.5063,  1.0934, -4.3770,  0.4817],
        [ 3.5295, -4.1107,  1.7744,  0.1032],
        [ 2.7068, -2.3518, -2.9924, -2.2361]])


/home/taeho/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  


In [57]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))
# matrix multiplication
z = torch.mm(x, y)
print(z.size())

torch.Size([4, 4])


In [58]:
x.data

tensor([[-0.1543,  4.2907,  0.2236, -2.8022],
        [-2.0575, -0.5636, -0.8188,  0.1090],
        [-1.3117, -1.6458,  1.7566,  1.8466],
        [-1.3897,  2.1993, -1.2817,  0.7104]])

In [59]:
#tensor operations

In [60]:
mat1 = torch.FloatTensor(4,4).uniform_(0,1)
mat1

tensor([[0.9847, 0.5323, 0.5292, 0.4766],
        [0.7693, 0.4567, 0.5488, 0.3049],
        [0.5636, 0.7567, 0.7661, 0.9689],
        [0.5449, 0.0366, 0.1953, 0.2597]])

In [61]:
mat2 = torch.FloatTensor(5,4).uniform_(0,1)
mat2

tensor([[0.4608, 0.0832, 0.9002, 0.9188],
        [0.1386, 0.3701, 0.1947, 0.2268],
        [0.9587, 0.2615, 0.7256, 0.7673],
        [0.5667, 0.1863, 0.4642, 0.4016],
        [0.9981, 0.8452, 0.5569, 0.7666]])

In [62]:
vec1 = torch.FloatTensor(4).uniform_(0,1)
vec1

tensor([0.1084, 0.7874, 0.7348, 0.9939])

In [63]:
# scalar addition

In [64]:
mat1 + 10.5

tensor([[11.4847, 11.0323, 11.0292, 10.9766],
        [11.2693, 10.9567, 11.0488, 10.8049],
        [11.0636, 11.2567, 11.2661, 11.4689],
        [11.0449, 10.5366, 10.6953, 10.7597]])

In [65]:
# scalar subtraction

In [66]:
mat2 - 0.20

tensor([[ 0.2608, -0.1168,  0.7002,  0.7188],
        [-0.0614,  0.1701, -0.0053,  0.0268],
        [ 0.7587,  0.0615,  0.5256,  0.5673],
        [ 0.3667, -0.0137,  0.2642,  0.2016],
        [ 0.7981,  0.6452,  0.3569,  0.5666]])

In [67]:
# vector and matrix addition

In [68]:
mat1 + vec1

tensor([[1.0931, 1.3196, 1.2640, 1.4705],
        [0.8777, 1.2440, 1.2836, 1.2988],
        [0.6720, 1.5441, 1.5009, 1.9628],
        [0.6533, 0.8239, 0.9301, 1.2536]])

In [69]:
mat2 + vec1

tensor([[0.5692, 0.8706, 1.6350, 1.9127],
        [0.2470, 1.1574, 0.9295, 1.2207],
        [1.0672, 1.0489, 1.4604, 1.7613],
        [0.6751, 0.9737, 1.1990, 1.3955],
        [1.1066, 1.6325, 1.2917, 1.7605]])

In [70]:
# matrix-matrix addition

In [71]:
mat1 + mat2

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [72]:
mat1 * mat1

tensor([[0.9695, 0.2833, 0.2801, 0.2271],
        [0.5918, 0.2085, 0.3012, 0.0930],
        [0.3176, 0.5726, 0.5870, 0.9387],
        [0.2970, 0.0013, 0.0381, 0.0674]])

In [73]:
# about Bernoulli distribution

In [74]:
from torch.distributions.bernoulli import Bernoulli

In [75]:
dist = Bernoulli(torch.tensor([0.3,0.6,0.9]))

In [76]:
dist.sample() #sample is binary, it takes 1 with p and 0 with 1-p

tensor([0., 1., 0.])

In [77]:
#Creates a Bernoulli distribution parameterized by probs 
#Samples are binary (0 or 1). They take the value 1 with probability p 
#and 0 with probability 1 - p.

In [78]:
from torch.distributions.beta import Beta

In [79]:
dist = Beta(torch.tensor([0.5]), torch.tensor([0.5]))
dist

Beta()

In [80]:
dist.sample()

tensor([0.3572])

In [81]:
from torch.distributions.binomial import Binomial

In [82]:
dist = Binomial(100, torch.tensor([0 , .2, .8, 1]))

In [83]:
dist.sample()

tensor([  0.,  20.,  80., 100.])

In [84]:
# 100- count of trials
# 0, 0.2, 0.8 and 1 are event probabilities

In [85]:
from torch.distributions.categorical import Categorical

In [86]:
dist = Categorical(torch.tensor([ 0.20, 0.20, 0.20, 0.20, 0.20 ]))
dist

Categorical(probs: torch.Size([5]))

In [87]:
dist.sample()

tensor(1)

In [88]:
# 0.20, 0.20, 0.20, 0.20,0.20 event probabilities

In [89]:
# Laplace distribution parameterized by loc and ‘scale’.

In [90]:
from torch.distributions.laplace import Laplace

In [91]:
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.990]))
dist

Laplace(loc: torch.Size([1]), scale: torch.Size([1]))

In [92]:
dist.sample()

tensor([10.0258])

In [93]:
#Normal (Gaussian) distribution parameterized by loc and ‘scale’.

In [94]:
from torch.distributions.normal import Normal

In [95]:
dist = Normal(torch.tensor([100.0]), torch.tensor([10.0]))
dist

Normal(loc: torch.Size([1]), scale: torch.Size([1]))

In [96]:
dist.sample()

tensor([97.7182])